nextmcloud/nmctheme

- .eslintrc.cjs
- .github/workflows/nmc-app-release.yml
- appinfo/info.xml
- js/icons.js
- js/nmcfooter.js
- package-lock.json
- package.json
- stylelint.config.js
- Use the new release workflow with fast-fail app-precheck and prerelease marking
- Make eslint working, apply on existing js files, handle a non-removable warning
- Simplify theme registration
- increase release number
> [devops] Automation, quality and code housekeeping

- l10n/de.json
- l10n/de_DE.json
- l10n/en.json
- l10n/en_GB.json
This PR adds the translations separate from the multiple L10N PRs so that all PRs can use them, independent of Nextcloud target version
> Initial translations

- lib/L10N/L10NResourceLocatorExtension.php
The injection and construction of JSResourceLocator is changing between V25, V26 and later.
We try to encapsulate this exception in constructor of our extension and support all Versions without
dedicated, version-based changes or patches.
> Translations: Add alternate constructors for V25, V26 for AppendService injection

- css/apps/files.scss
Styles regarding table row height, padding, thumbnail etc are now applied to all tables in Files app
> Apply styles for all tables in the files app

- css/apps/files.scss
- css/components/ncheadermenu.scss
- css/v25/header.scss
- css/v25/ncappnavigation.scss
- lib/Listener/BeforeTemplateRenderedListener.php
- src/components/UserMenu.vue
- src/js/filelistplugin.js
- webpack.config.cjs
Selection of all, or some items via checkbox results in customized visuals and behavior.
Header Checkbox is now labeled "All"
Header Entries aligned to Table content.
File Actions aligned right.
Removed additional actions.
Customizations apply as well to trashbin table view.
> Customize file selection

- l10n/de.json
- l10n/de_DE.json
- l10n/en.json
- l10n/en_GB.json
- src/components/StorageQuota.vue
Switched files size computation to GiB, and added some translations for "used" and "of"
> Fix filesize computations, use binary metrics

- l10n/de.json
- l10n/de_DE.json
- l10n/en.json
- l10n/en_GB.json
- src/js/nmcsettings.js
- we must avoid to show ANID=`username` anywhere. Always use `displayname`
- never forget to translate all text in Javascripts and on server with L10N
> Use displayname and translations in settings menu context

- css/components/ncappnavigation.scss
- css/components/nccheckbox.scss
- src/components/DisplaySettings.vue
- src/components/FilesSettings.vue
- src/components/StorageQuota.vue
This PR fixes the bug with incorrect storage stats title. Also contains minor style changes.
> Storage stats title fix, style cleanup

- css/apps/files.scss
- src/js/filelistplugin.js
Implemented green and round checkmarks
Change to round edges for the checkboxes 
Modified multiple selections actions layout
> added adaptations for filelist

- css/apps/viewer.scss
- css/nmcstyle.scss
This PR adds general styling for previewer app
> Previewer design

- css/apps/sharing.scss
- css/components/nccheckbox.scss
This PR contains minor style changes of sharing app and checkbox component
> General styling - sharing

- css/apps/files.scss
- css/apps/server.scss
- css/nmcstyle.scss
Selected text has magenta background and white text color
> added nmc wide selection rule

- css/apps/viewer.scss
css styles were not applied if German was a selected language
> Viewer design - minor fixes

- css/components/upload.scss
- css/nmcstyle.scss
- src/icons.mjs
This PR contains styles for the upload progress bar, which is displayed in the breadcrumb component of the files app
> Upload progress bar

- css/apps/settings.scss
> styling for custom settings components

- css/layouts/footer.scss
- l10n/en.json
- l10n/en_GB.json
https://jira.telekom.de/browse/NMC-2552
> Add line breaks for smartphone

- css/v25/ncappnavigation.scss
- l10n/de.json
- l10n/de_DE.json
- l10n/en.json
- l10n/en_GB.json
- lib/AppInfo/Application.php
- lib/NavigationManagerDecorator.php
- lib/Service/NMCFilesService.php
added modification class to rearrange and add navigation entries
run rearrange and add methods in nmctheme application, after all registrations have completed and boot method is executed.
> added modifications to files app navigation menu

- .eslintrc.cjs
- css/apps/files.scss
- css/components/tooltip.scss
- css/nmcstyle.scss
- l10n/de.json
- l10n/de_DE.json
- l10n/en.json
- l10n/en_GB.json
- lib/Listener/BeforeTemplateRenderedListener.php
- package-lock.json
- package.json
- src/js/shareicons.js
- src/js/tooltip.js
- webpack.config.cjs
This PR adds a functionality to generate icons for 'My shares' and 'Shared with me' views. It also adds global custom tooltip component.
> 'My shares' and 'Shared with me' views - icons

- css/layouts/footer.scss
- l10n/de.json
- l10n/de_DE.json
As discussed with @aleksei-nmc 10.10.
> revert footer column layout changes

- css/apps/files.scss
- l10n/de.json
- l10n/de_DE.json
- l10n/en.json
- l10n/en_GB.json
- lib/Service/NMCFilesService.php
- src/components/StorageQuota.vue
fixed alignment of navigation toggle and view toggle
new translations for file menu entries
switched shared by me and shared with me entries
force decimal file size units in storage quota (calculation remains binary)
> file list 100%

- css/apps/files_grid.scss
- css/nmcstyle.scss
File grid view layout changes:
- Star icon repositioned to center bottom
- Share button is hidden
> File grid view

- css/apps/apps.scss
- css/layouts/guestview.scss
- css/nmcstyle.scss
https://jira.telekom.de/browse/NMC-2542
https://jira.telekom.de/browse/NMC-2546
https://jira.telekom.de/browse/NMC-2609
> Restyle guest view for shared folders and files

- css/components/ncappmenu.scss
- css/layouts/header.scss
Design review comments in https://jira.telekom.de/browse/NMC-2554
> Restyle header spacings and font styles

- css/apps/media.scss
- css/components/ncactions.scss
- css/components/ncappnavigation.scss
- css/nmcstyle.scss
- img/icons/play-video.svg
- src/icons.mjs
> Media/Photos app - general styling

- css/apps/files.scss
- css/apps/settings.scss
- css/components/ncappnavigation.scss
- css/components/ncusermenu.scss
- css/layouts/modal.scss
- css/v25/ncappnavigation.scss
fixed alignment of icon in move and copy modal
fixed colors in move and copy modal
fixed some dark mode styles
> final touches to filelist and dialog boxes

- css/layouts/guestview.scss
https://jira.telekom.de/browse/NMC-2533
> Restyle password entry page for guest view only

- css/components/ncappmenu.scss
- css/components/ncheadermenu.scss
As requested in comment https://jira.telekom.de/browse/NMC-2554?focusedId=13452374&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13452374
> Remove all transition animations for header menu

- css/apps/viewer.scss
- css/components/ncactions.scss
- l10n/de.json
- l10n/de_DE.json
- l10n/en.json
- l10n/en_GB.json
- Change download and sidebar icons
- Change 'Open sidebar' label to 'Share'
> Viewer - icon and label updates

- css/apps/media.scss
- css/components/ncappnavigation.scss
- css/components/ncheadermenu.scss
Apply styles for Albums and Folders sections
> Media and albums

- css/layouts/header.scss
- css/v25/header.scss
main menu items (files & media) now have font-weight: 800
right menu items (search, account, ...) now have font-weight: normal
> Header - change font weight of labels

- css/apps/files-right-click.scss
Updated icon of 'View in folder' option
Fixed layout not working on 'My shares' and 'Shared with me' pages
> Right click menu

- css/_mixins.scss
- css/layouts/guestview.scss
Layout updates for guest view of file and folder
> Guest view - update layout

- css/_variables.scss
- css/apps/apps.scss
- css/apps/files.scss
- css/apps/settings.scss
- css/components/ncappnavigation.scss
- css/components/ncheadermenu.scss
- css/layouts/conflictdialog.scss
- css/layouts/footer.scss
- css/layouts/guestview.scss
- css/layouts/header.scss
- css/v25/ncappnavigation.scss
- src/js/conflictdialog.js
This PR includes style changes for 'File already exists' modal
- Scale secondary and primary styles are applied to all buttons
- Modal window is adapted to scale 'Standard small'
> File conflict dialog

- css/apps/files.scss
'Shared' and 'Restore' labels now hide on screens less than 1024px
> Hide 'Shared' label in mobile view

- css/apps/media.scss
- img/actions/hide-menu.svg
- src/icons.mjs
Change icon of the toggle button when sidebar is opened
> Sidebar navigation of Media app - Change hide menu icon

- css/apps/files.scss
Id selector on top of table layout affected grid view of files. This pr removes it
> Fix grid view layout

- css/apps/media.scss
- css/components/nccheckbox.scss
- src/components/DisplaySettings.vue
This pr contains:
- fix for double checkbox problem
- style for the disabled state of the checkbox
- checked checkboxes now have normal size
- minor layout fixes of media app
> Disarranged checkbox fix

- css/apps/media.scss
Changes on lines 39-46 , rest is just formatting with CSS style
https://jira.telekom.de/browse/NMC-2757
> Media - remove share button for Albums

- l10n/de.json
- l10n/de_DE.json
- l10n/en.json
- l10n/en_GB.json
Change is just under "photos" -> "Edit album details", rest is JSON reformatting.
E.g. 
"photos": {
"translations": {
"Photos": "Fotos",
"Edit album details": "Album umbenennen"
},
> Media - rename "Edit Album details"

- css/apps/media.scss
https://jira.telekom.de/browse/NMC-2763
> Media -> Remove menu entry "Shared with you"

- css/v25/ncappnavigation.scss
- src/icons.mjs
additionally partial fix for ticket 2703
> fix for sidebar menu on ipad/iphone

- css/layouts/login.scss
https://jira.telekom.de/browse/NMC-2727
https://jira.telekom.de/browse/NMC-2727?focusedId=13559911&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13559911
> FIX Windows - Email validation - Info text above the "Confirm" button is hard to read

- css/apps/media.scss
https://jira.telekom.de/browse/NMC-2761
> Media - Remove upload functionality from Add photos function

- package-lock.json
- package.json
- src/js/filelistplugin.js
- src/js/newfilemenuplugin.js
files are created with correct mime
> fixed file creation

- css/apps/media.scss
https://jira.telekom.de/browse/NMC-2765
Added changes requested in small ticket https://jira.telekom.de/browse/NMC-2756
> Restyle Media-> Album -> Add photos modal

- css/apps/media.scss
Contains style for empty album page in media app
> Empty album view

- css/apps/media.scss
https://jira.telekom.de/browse/NMC-2765
As requested by Jens in Review Call 15.11.
> Media -> Remove Title from Add Photos Modal

- css/apps/photos.scss
- css/nmcstyle.scss
https://jira.telekom.de/browse/NMC-2578
> Media Restyle Folder section

- l10n/de.json
- l10n/de_DE.json
- l10n/en.json
- l10n/en_GB.json
Changed internal server error texts
Add also clean English translation for "hidden file" label.
> Improve internal server error with less tech description

- lib/AppInfo/Application.php
- lib/Listener/CSPListener.php
Added additional rules for CSP content security policy e.g. media_source 'self' , default-src 'self'
https://jira.telekom.de/browse/NMC-2675
> Fix Files Impossible to download a video image on PRE1

- css/apps/photos.scss
- css/apps/sharing.scss
Updated album list
'Add to album' and other modals now have consistent styles
Minor changes to sharing app
> Photos app changes

- css/login/grant.scss
Following review results in https://jira.telekom.de/browse/NMC-2807
> Fix grant login window paragraph and button issue

- css/apps/files.scss
- css/apps/files_grid.scss
- css/nmcdefault.scss
https://jira.telekom.de/browse/NMC-2864
https://jira.telekom.de/browse/NMC-2866
> Add Darkmode styles styles for Files List and Grid view

- css/apps/files-right-click.scss
- css/apps/files_grid.scss
- css/components/ncusermenu.scss
- css/layouts/header.scss
- css/nmcdefault.scss
https://jira.telekom.de/browse/NMC-2865
> Add darkmode style for account profile, add files, sharing flyouts

- css/_mixins.scss
- css/apps/files_grid.scss
- css/layouts/modal.scss
- css/nmcdefault.scss
https://jira.telekom.de/browse/NMC-2867
Fix for https://jira.telekom.de/browse/NMC-2866
> Style darkmode Modals and Buttons, Fix Darkmode File Grid View Colors,

- css/apps/files.scss
- css/apps/files_grid.scss
- css/nmcdefault.scss
This pr contains rework of previous darkmode design for files table
- updated selectors for both table and grid view so that background color is applied in all cases
- introduced two variables for table row background (it gives more clarity since the telekom variables differ in light and dark modes)
- implement correct background color of rows in light mode
> Refactor darkmode for files table

- css/_mixins.scss
- css/apps/files-right-click.scss
- css/apps/photos.scss
- css/layouts/modal.scss
- css/nmcdefault.scss
> Flyouts and modals darkmode

- css/apps/files.scss
- css/nmcdefault.scss
- css/v25/ncappnavigation.scss
- src/icons.mjs
Fixed icon color inversion if dark mode is enforced through user settings.
Bonus: repositioned favorite star a little in file list view.
> adjusted icon color inversion

- css/apps/files.scss
- package-lock.json
- Remove "New Text"
- Add border to Add icon and set border radius
- Add padding for border to resemble a circle again
> Restyle v27 File Add Breadcrumb as in v25

- css/apps/files.scss
- remove "Sort by Size" table header column and Size row items
- fix text overflow for Deleted column header
- remove on hover/focus grey effect and outlines on table header column buttons
- restyle breadcrumb icon to trash; breadcrumb right chevron cannot be added in CSS, as for Deleted Files, the trash icon has been moved in the DOM from under .files-controls > ul.breadcrumb
- restyle context menu on table header checkbox select
- fix hover effect on column header items
- restyle checked icon color and style
- restyle chevron right separator icon for breadcrumbs
- restyle according to designs (spacings, black text etc.)
- restyle thumbnails
> Files App - Added features as per PR description

- css/apps/files.scss
- css/apps/photos.scss
- css/apps/rich-workspace.scss
- css/components/ncactions.scss
- css/components/ncappnavigation.scss
- css/components/ncfields.scss
- css/components/search.scss
Additionally to text editor adjustments, photos and files received minor fixes
> editor and other adjustments

- css/apps/files.scss
- css/apps/settings.scss
> Restyle welcome popup settings and remove set reminder from files popup menus

- css/apps/files.scss
- css/components/ncheadermenu.scss
https://jira.telekom.de/browse/NMC-2911
https://jira.telekom.de/browse/NMC-2917
https://jira.telekom.de/browse/NMC-2929
> Add Bug Fixes v27 Crowdtest

- css/apps/files.scss
> Fix popout menu bug on files grid view on click on empty space

- css/apps/files.scss
- css/apps/photos.scss
- css/apps/viewer.scss
https://jira.telekom.de/browse/NMC-2919
https://jira.telekom.de/browse/NMC-2939
> Fix additional bugs for files and photos apps

- css/apps/files.scss
https://jira.telekom.de/browse/NMC-2920
> Fix truncated editing tools bar for files folder info

- css/apps/files-right-click.scss
- css/apps/files.scss
- css/apps/settings.scss
- l10n/de.json
- l10n/de_DE.json
- l10n/en.json
- l10n/en_GB.json
- lib/AppInfo/Application.php
- lib/Listener/BeforeTemplateRenderedListener.php
- package-lock.json
- src/nmcfiles.ts
- src/utils/sidebar.js
- webpack.config.cjs
fixed some visual styles for files and settings view
added translations for files and settings view
added "cancel selection" file action to batch action menu
added "sharing status" file action to 3dot and rightclick menu
fixed file navigation order
> added multiple small fixes

- lib/AppInfo/Application.php
- lib/Service/NMCThemesService.php
Nextcloud changed the constructor of their themig service class.
We have to provide the correct arguments when initializing our own nmc themig service.
> fixed initialization of theming service

- css/apps/photos.scss
> Remove photos upload files menu item in breadcrumb New button

- css/apps/photos.scss
recently added css code hides the upload file option in the files view.
removed css code in order to have said option show again.
> Removed faulty css code

- css/components/ncactions.scss
https://jira.telekom.de/browse/NMC-3015
> add missing icons for files text editor callouts menu

- css/apps/files.scss
https://jira.telekom.de/browse/NMC-3392
> Align search input with icon in files move-copy modal
