.gitignore
.php-cs-fixer.dist.php
composer.json
composer.lock
css/nmcdefault.css
css/nmcdefault.scss
lib/AppInfo/Application.php
lib/Listener/BeforeTemplateRenderedListener.php
lib/Service/NMCThemesService.php
lib/Themes/Magenta.php
lib/Themes/MagentaDark.php
lib/Themes/TeleNeoWebFont.php
tests/bootstrap.php
tests/phpunit.xml
tests/unit/Service/NMCThemesServiceTest.php
tests/unit/Service/NMCThemesServiceTestCase.php

Redesign nmctheme to register own themes on boot without the need of an upstream server change.
The idea is to use Dependency Injection to override the ThemesService injected into
the system.
The new NMCThemesService handles the following cases:
- you can define the list of themes on boot in service registration
- you can set default theme to use (as a kind of alias)
- you can define a set of "static" themes to always include
- if no user theme is set, the default (either configured or from registration) is used

Nmctheme registration without server change

---

css/layouts/footer.scss
css/layouts/header.scss
css/layouts/login.scss
css/layouts/status.scss
css/layouts/user.scss
css/nmcdefault.scss
css/nmcstyle.scss
js/nmcfooter.js
lib/Listener/BeforeTemplateRenderedListener.php

Nextcloud does not support a footer components consistently, esp. not on user and public layout.
The PR adds Javascript that replaces the inconsistent <footer> elements with a uniform header structure
for all layouts.
It contains also the core adaptions needed in stylesheet to place content properly.
It does not support language translation yet.
The links are not taken from <link> metadata in header yet.

Poor mans footer component for theming

---

css/components/ncfields.scss
css/nmcstyle.scss

Take over the basic styling _only for body types that allow for inputs_.
This leads to a global override of the vue styles.
Help text and icon placement still need tuning

First version of NcInput and derived components with scale

---

lib/Listener/BeforeTemplateRenderedListener.php

Show status page also for server errors with status code >=500
These are in the range up to code<600.

Fix: Show status also for server errors

---

l10n/de.json
l10n/de_DE.json
l10n/en.json
l10n/en_GB.json

Add custom translations for end_to_end_encryption app, based on standard Nextcloud labels to avoid extra code customizations.

E2e encryption translations

---

css/layouts/footer.scss
css/layouts/header.scss
css/layouts/user.scss

Fixed header logo position and footer width as discussed in review call 7.8. 
Footer width changes with window resize, which does not apply to either #header or #content, so a longterm suggestion might be to rethink how footer is being displayed altogether, maybe with a position: relative to the entire screen (in that case need position from design maybe, and even in that case scrolling through the content would mean footer always stays on top at the bottom of the screen).

 (nmc 2480 v25stable) fix logo position and footer width

---

css/layouts/footer.scss
css/layouts/login.scss

With the consent layer working, some small layout fixings are done:
- pure transparency for footer
- non-disturbing color for footer text
- position of "classic" login window in case `/login?direct=1`

Fix login style for consent layer behavior

---

css/components/ncappnavigation.scss
css/components/nccheckbox.scss

To rebase from main and merge after https://github.com/nextmcloud/nmctheme/pull/65 is merged
- align checkboxes left with the navigation bar
- align checkboxes centered with the arrow of the open/close flip arrow
- align text right of checkboxes with the text right side of the open/close flip arrow

add alignment for arrow button, chkboxes and chkbox text

---

l10n/de.json
l10n/de_DE.json
l10n/en.json
l10n/en_GB.json
lib/L10N/FactoryDecorator.php
lib/Listener/BeforeTemplateRenderedListener.php

Fix temporary the app name of photos to emphasize media focus of app.
Photos app uses the label "Photos" as the name of the photos category within the app
AND add the navigation entry for the app. As the app also offers video management,
our PO wants a different name for the menu entry ("Media"), but this would also change the
name of the Photos category with the app.
We temporarily fix this by changing the nav entry to PhotosMedia before rendering public/user page.

Change photos app navigation entry to Medien/Media

---

lib/L10N/FactoryDecorator.php
tests/unit/L10N/DecoratorTest.php
tests/unit/L10N/FactoryTest.php

This PR fixes the exception on logging invalid appender L10N json files.
It now also delivers the error message.
A unittest is added that checks for syntactically valid L10N appender jons.

Fix log error message on invalid L10N json

---

l10n/de.json
l10n/de_DE.json
l10n/en.json
l10n/en_GB.json

Due to a merge fault, translation for Photos -> Media app are shifted to nmcsetting translations.
Shifting back should fix the problem.

Move translation from settings to theme

---

lib/Listener/BeforeTemplateRenderedListener.php
src/js/filelistplugin.js
src/js/newfilemenuplugin.js
webpack.config.cjs

changed the function to add a folder: the folder will be created called "New folder" or "Neuer Ordner" with an activated rename function
if the created folder is not inside the viewport, the screen will scroll down to the created item
if a folder called "Neuer Ordner" or "New folder" already exists, the created folder will have a counter like "New folder (2)

created newfilemenu plugin

---

README.adoc
lib/L10N/FactoryDecorator.php
tests/unit/L10N/DecoratorTest.php
tests/unit/L10N/FactorySupportedLangTest.php
tests/unit/L10N/FactoryTest.php
tests/unit/L10N/FactoryTestCase.php
tests/unit/L10N/L10nTest.php
tests/unit/UrlGeneratorDecoratorTest.php

The PR restricts the supported languages to those locales set  in the system variable `nmc_supported_locales`(see README)
This not only limits the number of entries in the user settings, but also prohibits request languages to enforce
languages supported by Nextcloud but NOT by MagentaCLOUD.

Restrict supported languages in theme

---

css/apps/apps.scss
css/apps/files.scss
src/components/filesSettings.utils.ts
src/index.d.ts

Display settings changes were not reflected on a page in v25. This PR fixes this by additionaly updating global filesConfig object.

Display settings -> Show hidden files/Crop image previews work only after refresh

---

src/js/newfilemenuplugin.js

This PR removes the 'Set up templates folder' option from the plus button in the breadcrumb

+Button > Remove the item 'set up templates folder'

---

l10n/de.json
l10n/de_DE.json
l10n/en.json
l10n/en_GB.json
lib/L10N/FactoryDecorator.php
tests/unit/L10N/FactorySupportedLangTest.php
tests/unit/L10N/FactoryTestCase.php

The method findAvailableLanguages returns an array in the following format: ['en','de','etc'].
Therefore the function 
in_array($locale['code'], $this->supported_locales) 
fails because of the undefined array key 'code'

fixed filtering of available languages

---

l10n/de.json
l10n/de_DE.json
l10n/en.json
l10n/en_GB.json
src/components/DisplaySettings.vue
src/components/filesSettings.utils.ts
src/store/userconfig.ts

This PR adds an option to the display settings menu that allows the user to control text workspace visibility

Display settings -> 'Show folder info text' option

---

l10n/de.json
l10n/de_DE.json
l10n/en.json
l10n/en_GB.json
lib/Listener/BeforeTemplateRenderedListener.php

We are loading header and footer relatively late, so that old Nextcloud fragments are shown - esp. on the login page.
Prioritized  header/footer to reloaded shortly after core.
Additionally, the entity patch for the percentage symbol in translations is taken back, breaking the unittests but fixing the visual problem. Entities seem not to be handled properly in Chrome.

Old artefacts due to lazy load sequence

---

src/js/shareicons.js

Display icon-link instead of icon-public if a file has only link shares and the user is on 'My shares' page

My shares - Fix incorrect icon display

---

css/apps/viewer.scss

Buttons in a viewer header for text documents now have correct colors

Viewer app - fix icon colors for dark and light modes

---

css/components/upload.scss

Label text color turns white when progress bar is in the background ![Screenshot 2023-10-13 115935](https://github.com/nextmcloud/nmctheme/assets/139760733/59d8cbe8-e192-442c-9f2a-3d0287bb26a8)

Upload bar - Set inner label color to white

---

css/_mixins.scss
css/components/ncappnavigation.scss
css/components/ncbuttons.scss
css/nmcdefault.scss
css/v25/ncappnavigation.scss
src/components/StorageQuota.vue

Fixes for sidebar navigation
- introduce global variable for #EDEDED color
- correct font and background color on hover
- 'Expand storage' button is styled to secondary button of Scale
- equal gap between navigation items

Sidebar navigation - styling fixes

---

src/js/shareicons.js

This pr fixes a bug where custom icons were not rendering if only one share exists for a file

My shares - fix icons not rendering if only one share exists

---

css/layouts/status.scss

https://jira.telekom.de/projects/NMC/issues/NMC-2609
As discussed on 19.10. in our review call, as the error page view is used in other scenarios as well, not only for file sharing expired link ("guest view"), only background image should be changed.

Change background image for error page view

---

src/js/filelistplugin.js
src/js/newfilemenuplugin.js

there was a bug in the multiselect menu. the menu was not closed after files are deleted and therefore no selection is active anymore.
the menu is now correctly closed after files are deleted.

fixed delete file bug

---

src/components/StorageQuota.vue

Format usage number to display only two digits after the decimal point

Storage quota - show two digits after comma

---

l10n/de.json
l10n/de_DE.json
l10n/en.json
l10n/en_GB.json

On the upstream app, 2 labels have changed and are not overridden anymore.
(we should thing about having a unittest for overrides not applying anymore in the future)
Note that labels will change again for V27 ff, which is already derivable from repo state!

Adopt translation to changed message labels for V25

---

lib/AppInfo/Application.php
lib/Search/SearchComposerDecorator.php

`getProviders` delivered a result json which contained empty fields 8due to wrong php indexing).
This is fixed.
As comments are not delivered yet, but no mentioned in search help text, it is additionally blacklisted.

No search providers shown on UI

---

css/components/ncheadermenu.scss
css/components/search.scss
css/nmcstyle.scss

https://jira.telekom.de/browse/NMC-2561
- Had to use !important a few times in search.scss, in order to override the styling in the following "core" components: SearchResult.vue & UnifiedSearch.vue --> Open to suggestions if we can do this any better way.

Restyle Unified Search & Results Popover

---

css/apps/media.scss

Hide links to pages 'Collaborative albums', 'People', 'On this day', 'Shared with me'  and 'Locations'

Media and albums - hide links in sidebar navigation

---

lib/Listener/CSPListener.php

the cps lister causes a fatal error by calling the undefined function getResponse.
The AddContentSecurityPolicyEvent delivers no response therefore this method has to be removed,
Instead the new policy settings hve to be added to the event.

fixed csp listener

---

css/apps/photos.scss
css/components/ncactions.scss
css/login/grant.scss
css/nmcstyle.scss

https://jira.telekom.de/browse/NMC-2807
As there was no way to test the login grant window locally, used the grant.php template as reference for the restyle.
PR includes:
- "fix close button style (as discussed in Review call 21.11) " from https://jira.telekom.de/browse/NMC-2765
- ""Add photos to album" leads directly to Add photos modal (no dropdown anymore)  (as discussed in Review Call 21.11, we can only remove the Upload files menu item, this is now done LP 22.11)" from https://jira.telekom.de/browse/NMC-2762

Restyle Login Grant Window and small changes in Media Add Photo Modal and 3-Dot-Menu

---

l10n/de.json
l10n/de_DE.json
l10n/en.json
l10n/en_GB.json

there are two different variations of the same translation key for the encryption text, which depends which version of the end to end encryption app is deployed.
additionally some translations that are needed for the theming page are included.

added uppercase translation variant

---

css/apps/rich-workspace.scss

removed variables overrides, that lead to inconsistent coloring of the callout blocks

removed color overrides

---

css/apps/photos.scss

Photo previewer should not rely on the custom variable for it's background color

Fix photo preview background color

---

css/apps/settings.scss

Fix trashbin icon cutoff for welcome popup settings

---

appinfo/routes.php
lib/Controller/TouchIconController.php
lib/URLGeneratorDecorator.php

FIXES: https://jira.telekom.de/browse/NMC-3047
In order to replace the touch icon that is used for the sharelink preview, when pasted into messengers etc.
we replaced the route that is called from standard theming manifest file with our custom one.
Our current customizations have not had any effect, because the imagePath method is not used to access the file.

created alternative touch icon route
